job:
  script: echo "Hello, Rules!"
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        WORKING_BRANCH: staging
        PATH: yilin-workspace-staging
        RUNNER: staging-runner

    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        WORKING_BRANCH: develop
        PATH: yilin-workspace-dev
        RUNNER: dev-runner

building:
  stage: build
  script:
    - cd /var/www/$PATH
    - sudo git reset --hard
    - sudo git pull origin $WORKING_BRANCH
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - sudo npm install
    - sudo npm run build:admin
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - $WORKING_BRANCH
  tags:
    - $RUNNER
