before_script:
- echo "Before script"
- cd /var/www/yilin-workspace-dev
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin develop
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - sudo php artisan cache:clear
    - php artisan config:clear
    - sudo npm install
    - sudo npm run build:admin
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart # if you use queue
