variables:
  WORKING_BRANCH: staging
  PATH: yilin-workspace-staging
  RUNNER: staging-runner

building:
  stage: build
  script:
    - cd /var/www/$PATH
    - sudo git reset --hard
    - sudo git pull origin $WORKING_BRANCH
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - sudo npm install
    - sudo npm run build:admin
  only:
    - $WORKING_BRANCH
  tags:
    - $RUNNER

testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
  only:
    - $WORKING_BRANCH
  tags:
    - $RUNNER

deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - $WORKING_BRANCH
  tags:
    - $RUNNER
