before_script:
  - cd /var/www/yilin-workspace-staging

building:
  stage: build
  script:
    - git reset --hard origin/staging
    - git pull origin staging
    - composer install --optimize-autoloader --no-dev
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - npm install
    - npm run build:admin
  only:
    - staging
  tags:
    - staging-runner
