before_script:
  - echo "Before script"
  - cd /var/www/yilin-workspace-dev
building:
  stage: build
  script:
    - groups
    - git config --global --add safe.directory /var/www/yilin-workspace-dev
    - git reset --hard
    - git pull origin develop
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - npm install
    - npm run build:admin
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
