before_script:
  - cd /var/www/yilin-workspace-staging

building:
  stage: build
  script:
    - git reset --hard
    - git pull origin staging
    - composer install --optimize-autoloader --no-dev
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan view:cache
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - sudo npm install
    - sudo npm run build:admin
  only:
    - staging
  tags:
    - staging-runner

testing:
  stage: test
  script:
    - sudo vendor/bin/phpunit --migrate-configuration
    - sudo php ./vendor/bin/phpunit
  only:
    - staging
  tags:
    - staging-runner

deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - staging
  tags:
    - staging-runner
