building:
  stage: build
  script:
    - cd /var/www/yilin-workspace-staging
    - sudo git reset --hard
    - sudo git pull origin staging
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - sudo npm install
    - sudo npm run build:admin
  only:
    - staging
  tags:
    - staging-runner

testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
  only:
    - staging
  tags:
    - staging-runner

deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - staging
  tags:
    - staging-runner
