before_script:
  - sudo su - deployer
  - cd /var/www/yilin-workspace-dev
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin develop
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chmod -R 775 storage
    - npm install
    - sudo npm run build:admin
  only:
    - develop
  tags:
    - dev-runner

testing:
  stage: test
  script:
    - sudo php artisan test
  only:
    - develop
  tags:
    - dev-runner
deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - develop
  tags:
    - dev-runner
