data = ['Credit_Card_Exceed_Months',N'umber_of_Dependents',N'umber_of_Credit_Card_Facility',
'Number_of_Properties', 'Number_of_Bank_Products',
'Number_of_Loan_to_Approve',N'umber_of_Side_Income', 'Monthly_Salary',
'Total_Income_for_Join_Application',
'Employment_Type_Self_Employed', 'Employment_Type_employee',
'Employment_Type_employer', 'Employment_Type_government',
'Credit_Card_types_normal', 'Credit_Card_types_platinum',
'Property_Type_condominium', 'Property_Type_flat',
'Property_Type_terrace', 'State_Kedah', 'State_Sabah',
'State_Sarawak', 'State_Sembilan', 'State_Trengganu']
